
services:
  postgres:
    build:
      context: ./BD
      dockerfile: dockerfile
    container_name: postgres_escola
    restart: always
    environment:
      DATA_SOURCE_NAME: "postgresql://faat:faat@postgres_escola:5432/Escola?sslmode=disable"
      POSTGRES_DB: Escola
      POSTGRES_USER: faat
      POSTGRES_PASSWORD: faat
    ports:
      - "2000:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  postgres_exporter:
    image: prometheuscommunity/postgres-exporter:latest
    container_name: postgres_exporter
    restart: always
    environment:
      DATA_SOURCE_NAME: "postgresql://admin:secretpassword@postgres_escola:5432/school_db?sslmode=disable"
    ports:
      - "9187:9187"

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    restart: always
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    restart: always
    ports:
      - "3000:3000"
    volumes:
      - grafana_data:/var/lib/grafana

volumes:
  postgres_data:
  grafana_data: